# Generated by Django 5.0.7 on 2024-08-07 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100)),
                ('engine_number', models.CharField(max_length=100)),
                ('transmission_number', models.CharField(max_length=100)),
                ('number_drive_bridge', models.CharField(max_length=100)),
                ('controlled_bridge_number', models.CharField(max_length=100)),
                ('delivery_agreement', models.CharField(max_length=100)),
                ('date_of_shipment', models.DateField()),
                ('consignee', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=300)),
                ('package_contents', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_TO', to=settings.AUTH_USER_MODEL)),
                ('controlled_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridge_model', to='silant.controlledbridge')),
                ('model_drive_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_drive_bridge', to='silant.drivebridge')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='silant.engine')),
                ('model_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_technique', to='silant.technique')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='silant.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refusal', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('description_failure', models.TextField()),
                ('spare_parts_used', models.TextField(blank=True)),
                ('date_restoration', models.DateField()),
                ('equipment_downtime', models.IntegerField(default=0)),
                ('car_complaints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_complaints', to='silant.car')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_complaints', to=settings.AUTH_USER_MODEL)),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='silant.failurenode')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='silant.recoverymethod')),
            ],
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('order', models.CharField(max_length=100)),
                ('date_order', models.DateField()),
                ('car_TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_of_TO', to='silant.car')),
                ('organization_that_conducted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_that_conducted', to='silant.servicecompany')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL)),
                ('view_TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_TO', to='silant.viewto')),
            ],
        ),
    ]
