# Generated by Django 5.0.7 on 2024-08-19 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Company'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_company_TO', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Company'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_company_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='to',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Company'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
