# Generated by Django 5.0.7 on 2024-08-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_car_client_alter_car_service_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['date_of_shipment']},
        ),
    ]
